- src/main.py
- test/test_main.py
*Issue #, if available:* 14
*Description of changes:* Added support for ECR public repository + documentation changes
> change: Added support for ECR public repository + documentation changes

- README.md
*Description of changes:* Update documentation to reflect image's addition to SageMaker Studio, as well as provide guidance for installing additional packages
> chore: Update documentation

- template/Dockerfile
….
*Issue #, if available:* https://github.com/aws/sagemaker-distribution/issues/42
*Description of changes:* Install Git as part of the Dockerfile 
> feature: Install Git as part of the Dockerfile 

- README.md
*Description of changes:* Removing "Beta" terms from README
> chore: Remove 'beta' section from README

- test/test_dockerfile_based_harness.py
Updated tests to run docker containers in a detached manner.
In some occurrences, we are not able to print docker failure logs because container was marked for deletion
> fix: Update tests to run docker containers in a detached manner

- test/test_artifacts/v0/scripts/run_pysdk_tests.sh
- test/test_artifacts/v0/sm-python-sdk.test.Dockerfile
*Issue #, if available:* https://github.com/aws/sagemaker-distribution/issues/54
*Description of changes:* fix SageMaker Python SDK tests
> fix: fix SageMaker Python SDK tests

- test/test_artifacts/v1/autogluon.test.Dockerfile
- test/test_artifacts/v1/boto3.test.Dockerfile
- test/test_artifacts/v1/jupyter-ai.test.Dockerfile
- test/test_artifacts/v1/keras.test.Dockerfile
- test/test_artifacts/v1/matplotlib.test.Dockerfile
- test/test_artifacts/v1/numpy.test.Dockerfile
- test/test_artifacts/v1/pandas.test.Dockerfile
- test/test_artifacts/v1/pytorch.examples.Dockerfile
- test/test_artifacts/v1/run_pandas_tests.py
- test/test_artifacts/v1/scipy.test.Dockerfile
- test/test_artifacts/v1/scripts/run_autogluon_tests.sh
- test/test_artifacts/v1/scripts/run_boto3_tests.sh
- test/test_artifacts/v1/scripts/run_keras_tests.sh
- test/test_artifacts/v1/scripts/run_matplotlib_tests.sh
- test/test_artifacts/v1/scripts/run_pysdk_tests.sh
- test/test_artifacts/v1/sm-python-sdk.test.Dockerfile
- test/test_artifacts/v1/tensorflow.examples.Dockerfile
- test/test_artifacts/v1/tensorflow/run_tensorflow_example_notebooks.sh
- test/test_dockerfile_based_harness.py
This PR adds `jupyter-ai` to SM distribution. Here is the update need to `build_artifacts/v1/v1.0/v1.0.0/v1.0.0-beta/cpu.env.in` and `build_artifacts/v1/v1.0/v1.0.0/v1.0.0-beta/gpu.env.in` files.
```
conda-forge::jupyter-ai[version='>=2.2.0,']
```
> Added jupyter-ai

- build_artifacts/v0/v0.0/v0.0.1/RELEASE.md
- build_artifacts/v0/v0.0/v0.0.2/RELEASE.md
- build_artifacts/v0/v0.1/v0.1.0/RELEASE.md
- build_artifacts/v0/v0.1/v0.1.1/RELEASE.md
- build_artifacts/v0/v0.1/v0.1.2/RELEASE.md
- build_artifacts/v0/v0.2/v0.2.0/RELEASE.md
- build_artifacts/v0/v0.2/v0.2.1/RELEASE.md
- build_artifacts/v0/v0.2/v0.2.2/RELEASE.md
- build_artifacts/v0/v0.3/v0.3.0/RELEASE.md
- build_artifacts/v0/v0.4/v0.4.0/RELEASE.md
- build_artifacts/v0/v0.4/v0.4.1/RELEASE.md
- build_artifacts/v0/v0.4/v0.4.2/RELEASE.md
- build_artifacts/v0/v0.4/v0.4.3/RELEASE.md
- build_artifacts/v0/v0.4/v0.4.4/RELEASE.md
- build_artifacts/v0/v0.5/v0.5.0/RELEASE.md
- build_artifacts/v0/v0.5/v0.5.1/RELEASE.md
- build_artifacts/v0/v0.6/v0.6.0/RELEASE.md
- build_artifacts/v0/v0.7/v0.7.0/RELEASE.md
- src/main.py
- src/release_notes_generator.py
- test/test_main.py
*Description of changes:* Add release notes generator for SageMaker distribution
> feature: Add release notes generator for SageMaker distribution

- test/test_artifacts/v1/numpy.test.Dockerfile
*Issue #, if available:* n/a
*Description of changes:* Adds a new required dependency for running the test suite.
> Fix numpy tests for versions 1.26+

- test/test_artifacts/v1/autogluon.test.Dockerfile
> Fix Autogluon test infra

- test/test_artifacts/v1/pandas.test.Dockerfile
- test/test_artifacts/v1/run_pandas_tests.py
*Description of changes:* Adds missing dependencies for pandas tests, ignores failing test case, and add `--no-strict-data-files` to fix many errors
> Fix broken pandas tests

- template/Dockerfile
*Issue #, if available:* https://github.com/aws/sagemaker-distribution/issues/117
*Description of changes:* Adding openssh-client to the dockerfile for future releases
> feature: Add OpenSSH client to the Dockerfile for future installations

- template/Dockerfile
*Description of changes:*  Set the USER environment variable. Some Applications might rely on USER environment variable.
> fix: Set the USER environment variable

- build_artifacts/v1/v1.4/v1.4.0/cpu.additional_packages_env.in
- build_artifacts/v1/v1.4/v1.4.0/gpu.additional_packages_env.in
- test/test_artifacts/v1/serve.test.Dockerfile
- test/test_dockerfile_based_harness.py
https://github.com/aws/sagemaker-distribution/issues/143
Adding serving libs, plus LangChain to sagemaker distribution.
> Add langchain and serving components

- src/utils.py
*Description of changes:* update conda import to match new path (https://github.com/conda/conda/pull/13168). Else any new installation of the conda env will fail, such as the[ release workflow](https://github.com/aws/sagemaker-distribution/actions/runs/8054021827/job/21997656137)
> fix: Fix conda import

- .github/workflows/build-image.yml
*Description of changes:* Need to update ARN to be one generated by CDK. Also moving this role ARN to Secrets,
> fix: Use correct codebuild role

- build_artifacts/v1/v1.6/v1.6.0/cpu.additional_packages_env.in
- build_artifacts/v1/v1.6/v1.6.0/gpu.additional_packages_env.in
- test/test_artifacts/v1/jupyter-server-fileid.test.Dockerfile
- test/test_artifacts/v1/jupyter-ydoc.test.Dockerfile
- test/test_dockerfile_based_harness.py
N/A
release v1.6.0
**Testing Done**
python3 src/main.py create-minor-version-artifacts --base-patch-version=$BASE_PATCH_VERSION --force 
python3 src/main.py build --target-patch-version=$NEXT_VERSION
> feature: Add jupyter_ydoc and jupyter_server_fileid

- template/v0/Dockerfile
- template/v1/Dockerfile
*Issue #, if available:* https://github.com/aws/sagemaker-distribution/issues/189, https://github.com/aws/sagemaker-distribution/issues/128
*Description of changes:* Adds utility packages to fix bug and address feature request, see issues linked above. Also includes a syntax fix in a util file to unblock local builds.
> Add cron and less packages

- build_artifacts/v1/v1.6/v1.6.0/cpu.additional_packages_env.in
- build_artifacts/v1/v1.6/v1.6.0/gpu.additional_packages_env.in
- test/test_artifacts/v1/amazon-sagemaker-sql-magic.test.Dockerfile
- test/test_artifacts/v1/amazon_sagemaker_sql_editor.test.Dockerfile
- test/test_dockerfile_based_harness.py
Added new conda-forge dependencies amazon_sagemaker_sql_editor and amazon-sagemaker-sql-magic and their corresponding tests.
> feature: Add dependencies for amazon-sagemaker-sql extension

- template/v1/dirs/usr/local/bin/start-jupyter-server
* Updated `start-jupyter-server` script to start jupyterlab app in rtc mode for shared spaces.
> Added condition to run jupyterlab in RTC mode

- build_artifacts/v1/v1.6/v1.6.0/cpu.additional_packages_env.in
- build_artifacts/v1/v1.6/v1.6.0/gpu.additional_packages_env.in
- test/test_artifacts/v1/jupyter-server-fileid.test.Dockerfile
- test/test_artifacts/v1/jupyter-ydoc.test.Dockerfile
- test/test_dockerfile_based_harness.py
This reverts commit 166d95bb76e6d8cf555d5245b292dffc55d87b4d.
*Description of changes:* had issues getting the rest of the needed dependencies for feature in 1.6; removing now
> Revert "feature: Add jupyter_ydoc and jupyter_server_fileid (#198)"

- template/v1/dirs/usr/local/bin/start-jupyter-server
**Description**
Fixed the if-condtion when starting jupyter-server in RTC mode.
**Testing Done**
bb release
> Fix jupyter-server start script

- CONTRIBUTING.md
- template/v1/Dockerfile
- test/test_artifacts/v1/sagemaker-code-editor.test.Dockerfile
- test/test_artifacts/v1/scripts/run_sagemaker_code_editor_tests.sh
…rectly; Updated tests for sagemaker-code-editor
1. Updated Dockerfile so that all the extensions test file is parsed correctly regardless of a new line at the end 
2. Updated tests for sagemaker-code-editor to check for extensions, settings file
3. Updated CONTRIBUTING.md to include common pytest commands
> Updated tests for sagemaker-code-editor

- .github/workflows/nightly-build-image.yml
*Description of changes:* Adding nightly-build-image.yml to mainline
> Adding nightly-build-image.yml to mainline

- .github/workflows/nightly-build-image.yml
*Description of changes:* Adding audience to nightly-build-image.yml
> Adding audience to nightly-build-image.yml

- .github/workflows/nightly-build-image.yml
*Description of changes:* Adding id-token write permissions
> Adding id-token write permissions

- .github/workflows/nightly-build-image.yml
*Description of changes:* Enabling cron expression on nightly builds
> Enabling cron expression on nightly builds

- .github/workflows/nightly-build-image.yml
*Description of changes:* Enabling cron expression for nightly builds
> Enabling cron expression for nightly builds

- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/etc/supervisor/conf.d/supervisord-maxdome.conf
- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/usr/local/bin/entrypoint-maxdome-jupyter-server
- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/usr/local/bin/start-maxdome-default-jupyter-server
- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/usr/local/bin/start-maxdome-jupyter-server
- template/v2/dirs/etc/supervisor/conf.d/supervisord-maxdome.conf
- template/v2/dirs/usr/local/bin/entrypoint-maxdome-jupyter-server
- template/v2/dirs/usr/local/bin/start-maxdome-default-jupyter-server
- template/v2/dirs/usr/local/bin/start-maxdome-jupyter-server
Add entrypoint for non-default maxdome
docker run -it -p 8888:8888 --entrypoint entrypoint-maxdome-jupyter-server <docker-image-id>
> Add entrypoint for non-default maxdome

- template/v1/dirs/etc/jupyter/jupyter_server_config.py
- template/v2/dirs/etc/jupyter/jupyter_server_config.py
- test/test_artifacts/v2/run_pandas_tests.py
No logic changes, fixing the files based on the recommended checkstyle.
> Fixes for checkstyle

- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/etc/maxdome/kernels/glue_pyspark/kernel.json
- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/etc/maxdome/kernels/glue_spark/kernel.json
- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/etc/maxdome/kernels/kernel_launchers/glue_kernel_launcher.sh
- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/etc/maxdome/kernels/kernel_launchers/python3_kernel_launcher.sh
- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/etc/maxdome/kernels/python3/kernel.json
- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/usr/local/bin/entrypoint-maxdome-default-jupyter-server
- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/usr/local/bin/entrypoint-maxdome-jupyter-server
- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/usr/local/bin/start-maxdome-default-jupyter-server
- template/v2/dirs/etc/maxdome/kernels/glue_pyspark/kernel.json
- template/v2/dirs/etc/maxdome/kernels/glue_spark/kernel.json
- template/v2/dirs/etc/maxdome/kernels/kernel_launchers/glue_kernel_launcher.sh
- template/v2/dirs/etc/maxdome/kernels/kernel_launchers/python3_kernel_launcher.sh
- template/v2/dirs/etc/maxdome/kernels/python3/kernel.json
- template/v2/dirs/usr/local/bin/entrypoint-maxdome-default-jupyter-server
- template/v2/dirs/usr/local/bin/entrypoint-maxdome-jupyter-server
- template/v2/dirs/usr/local/bin/start-maxdome-default-jupyter-server
- test/test_artifacts/v2/maxdome_toolkit_cli.test.Dockerfile
Chores: Fix SAGEMAKER_APP_TYPE_LOWERCASE, reorganize kernel_launcher scripts, Modify kernel launcher for python3
> Chores: Fix SAGEMAKER_APP_TYPE_LOWERCASE, reorganize kernel_launcher

- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/Dockerfile
- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/etc/maxdome/get_credential.sh
- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/usr/local/bin/start-maxdome-default-jupyter-server
- template/v2/Dockerfile
- template/v2/dirs/etc/maxdome/get_credential.sh
This commit contains 3 changes:
1. continue to update usage of MaxDome CLI
2. configure aws profile before git
3. fix merge conflicts
> Chore: Update CLI usage, fix merge 

- template/v0/Dockerfile
- template/v1/Dockerfile
*Issue #, if available:* https://github.com/aws/sagemaker-distribution/issues/283
*Description of changes:* Add mandoc to resolve aws cli help issue
> fix: Add mandoc

- build_artifacts/v1/v1.7/v1.7.0/cpu.additional_packages_env.in
- build_artifacts/v1/v1.7/v1.7.0/gpu.additional_packages_env.in
- template/v1/Dockerfile
- template/v1/dirs/usr/local/bin/start-jupyter-server
- test/test_artifacts/v1/jupyter-collaboration.test.Dockerfile
- test/test_dockerfile_based_harness.py
> Add RTC extension and scripts

- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/etc/maxdome/maxdome_post_startup.sh
- template/v2/dirs/etc/maxdome/maxdome_post_startup.sh
Issue #, if available:
Description of changes:
--> This Commit will add the Post Container Git Clone script .
--> This script will be executed when the user App request comes on the existing container for MaxDome Use case .
Testing
--> Tested the changes locally , but have not tested E2E.
> Add Post-container GitClone Script for MaxDome use case

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Add issue templates:
- Bug Report
- Feature request
> Add issue templates for SMD repo

- template/v0/Dockerfile
- template/v1/Dockerfile
*Description of changes:* Upgrading system packages and npm, to avoid potential vulnerabilities from outdated versions
> fix: Upgrade system packages and npm

- CONTRIBUTING.md
- DEVELOPMENT.md
- README.md
*Description of changes:* Minor readme fixes to fix permissions issues when running image locally
> fix: Minor readme fixes

- README.md
- supported_images.md
Create a table including a full list of supported SageMaker Distribution image versions. Linked from README.
> Create supported image versions table

- template/v1/dirs/etc/jupyter/jupyter_server_config.py
This reverts commit 9695c95f65a651eb6c7b4976d5f44b706f9dbe00.
*Description of changes:* This change is no longer being added to the image
> Revert "feature: Make amazon q default language model (#443)"

- support_policy.md
set planned end of support date for SMD 0.13.0
> set planned end of support date for SMD 0.13.0

- support_policy.md
> Add 1.10 to support policy with EOS date

- support_policy.md
> Add v2 to support policy

- src/config.py
- template/v3/Dockerfile
- template/v3/dirs/etc/code-editor/code_editor_machine_settings.json
- template/v3/dirs/etc/code-editor/extensions.txt
- template/v3/dirs/etc/conda/.condarc
- template/v3/dirs/etc/jupyter/jupyter_server_config.py
- template/v3/dirs/etc/supervisor/conf.d/supervisord-code-editor.conf
- template/v3/dirs/etc/supervisor/conf.d/supervisord-common.conf
- template/v3/dirs/etc/supervisor/conf.d/supervisord-jupyter-lab.conf
- template/v3/dirs/etc/supervisor/conf.d/supervisord.conf
- template/v3/dirs/usr/local/bin/entrypoint-code-editor
- template/v3/dirs/usr/local/bin/entrypoint-jupyter-server
- template/v3/dirs/usr/local/bin/restart-jupyter-server
- template/v3/dirs/usr/local/bin/start-code-editor
- template/v3/dirs/usr/local/bin/start-jupyter-server
*Description of changes:* Adding initial template/config to unblock building candidate images. These can be edited up until release, but are needed for the workflow to build the new image. 
> add initial template, config for v3

- template/v1/dirs/etc/code-editor/extensions.txt
- template/v2/dirs/etc/code-editor/extensions.txt
- template/v3/dirs/etc/code-editor/extensions.txt
Update CodeEditor extension versions
> Update CodeEditor extension versions

- support_policy.md
> Add 2.2 support policy info

- template/v0/Dockerfile
- template/v1/Dockerfile
- template/v2/Dockerfile
- template/v3/Dockerfile
clean micromamba after install to reduce images size
the clean command needs to be run as root
> fix: clean micromamba after install

- support_policy.md
Move v0.13, v1.6 - v1.9 images to End-of-support section
> Update supported image versions in support_policy.md

- support_policy.md
> Update support policy for 2.3, 1.12

- .github/workflows/validate-image.yml
Add step to checkout repository to Image Validation Action, to get rid of failure: https://github.com/aws/sagemaker-distribution/actions/runs/13776624207
> Add step to checkout repository

- support_policy.md
1. Add entry for 2.4.0
2. Fix wrong image platform in unsupported list
> Update support policy

- support_policy.md
> Add 1.13.x to Support Image tables

- support_policy.md
*Description of changes:* Adding SMD 3.0.0 to support policy. Also moving 1.12.x so all versions are in order
> Add SMD 3.0 to support policy

- template/v1/dirs/etc/code-editor/extensions.txt
- template/v2/dirs/etc/code-editor/extensions.txt
- template/v3/dirs/etc/code-editor/extensions.txt
Updating CodeEditor Jupyter extension to latest version
Context:
https://quip-amazon.com/qrflAFrFTKQy/CodeEditor-Keeping-packaged-extensions-up-to-date
Testing:
https://quip-amazon.com/SbZkADCBWsjK/CodeEditor-Updating-Jupyter-packaged-extensions-up-to-date-Manual
> Updating CodeEditor Jupyter extension to latest version

- template/v2/dirs/etc/sagemaker-ui/workflows/start-workflows-container.sh
- template/v2/dirs/etc/sagemaker-ui/workflows/workflow_client.py
- previous blueprint check code is not working for gamma environment because we were using the prod datazone endpoint only.  
- update the code logic to check if blueprint is enabled - `list_blueprint(managed=True)` to get the `blueprint_id` for the Workflows blueprint and then run a `get_blueprint_configuration` and check `enabledRegion` field.
- initialize datazone client with endpoint if there is one - this is to support datazone gamma endpoint. 
- verified changes in both prod IAD and gamma PDX. video demo will be sent along with this PR
> add Workflows blueprint check; only start local runner if it's enabled

- template/v2/dirs/etc/sagemaker-ui/jupyter/server/jupyter_server_config.py
- template/v2/dirs/etc/sagemaker-ui/workflows/sample_dag.py
- template/v2/dirs/etc/sagemaker-ui/workflows/workflow_client.py
- template/v2/dirs/etc/sagemaker/sm_pysdk_default_config.py
- test/test_dockerfile_based_harness.py
*Description of changes:* 
Some formatting issues were brought in with recent changes for 2.5.0. Ran following commands:
```
black --line-length=120 src test template
isort --profile black src test template
autoflake --in-place --expand-star-imports --ignore-init-module-imports --remove-all-unused-imports -r src test template
```
otherwise all future PRs will fail code quality check
> Fix all format issues

- build_artifacts/v2/v2.6/v2.6.0/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
Fixing the post startup script execution overriding config logic to be jupyterlab specific
> Fix the post startup script execution for CE apps

- environment.yml
update `environment.yml` with necessary dependencies, with version restriction, to make sure `staleness report` is generated properly
> update environment.yml with necessary dependencies

- support_policy.md
> fix support policy

- src/package_report.py
Add error handling for staleness report generation. Some new package's stats are not available.
> Add error handling for staleness report generation

- src/package_report.py
*Description of changes:* Addresses a few issues with dependency report generation:
1. We weren't specifying a channel, so we are querying anaconda default channels instead of conda-forge. This leads to error when package is on conda-forge, and ungraceful failure because we don't have error handling
2. Adds error handling for conda api call
3. Skips generation for patch release, since we don't add new packages and just leads to big empty table in comment ([example](https://github.com/aws/sagemaker-distribution/pull/649#issuecomment-2899127326))
4. Fixes image config parsing; we currently parse each major version configs, and then each variant for these configs, printing 3 sets of CPU and GPU as seen in above example. With this change we only parse target version's …
> Improvements for dependency report

- support_policy.md
[Link any related issues here]
[Any additional information that might be helpful for reviewers]
> update support date for 3.0.x

- template/v2/dirs/etc/sagemaker-ui/workflows/start-workflows-container.sh
- template/v3/dirs/etc/sagemaker-ui/workflows/start-workflows-container.sh
change the project directory path to "shared" for non-git projects
source: https://amzn-aws.slack.com/archives/C05HTGQ1DQX/p1750094817923269
toolkit commit to change the directory name: https://code.amazon.com/packages/MaxDomeToolkitJavascriptClient/commits/afc8bb9a00fd8e65b0a8987dced329c30666ed52
to update the path introduced in previous …
> fix(unified-storage): change project dir path from shared-files to shared

- template/v2/dirs/etc/sagemaker-ui/libmgmt/install-lib.sh
- template/v2/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
- template/v2/dirs/etc/sagemaker-ui/workflows/start-workflows-container.sh
- template/v3/dirs/etc/sagemaker-ui/libmgmt/install-lib.sh
- template/v3/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
- template/v3/dirs/etc/sagemaker-ui/workflows/start-workflows-container.sh
1. libmgmt script was still referring to `src/.libs.json` in unified storage projects -> fixed this to pick up the path based on project type
2. Multiple places were doing the same if else loop to determine the PROJECT_DIR. Moved this if-else to the post-startup script and exported it as an env var so it can be used in other places. 
N/A
Ran Post startup script in a workflows-enabled project. Verified no errors in Workflows script and libmgmt script. See …
> Adding env var for project storage path, updating path to libmgmt script

- support_policy.md
[Link any related issues here]
[Any additional information that might be helpful for reviewers]
> Update support policy for 2.8, 3.3

- build_artifacts/v2/v2.9/v2.9.0/cpu.additional_packages_env.in
- build_artifacts/v2/v2.9/v2.9.0/gpu.additional_packages_env.in
- build_artifacts/v3/v3.4/v3.4.0/cpu.additional_packages_env.in
- build_artifacts/v3/v3.4/v3.4.0/gpu.additional_packages_env.in
- test/test_artifacts/v2/uv.test.Dockerfile
- test/test_artifacts/v3/uv.test.Dockerfile
Add `uv` package https://anaconda.org/conda-forge/uv
[Link any related issues here]
[Any additional information that might be helpful for reviewers]
> add uv in next minor versions as requested by partner team

- build_artifacts/v3/v3.5/v3.5.0/cpu.additional_packages_env.in
- build_artifacts/v3/v3.5/v3.5.0/gpu.additional_packages_env.in
- template/v3/dirs/usr/local/bin/start-sagemaker-ui-jupyter-server
Add New Agentic Chat Gen AI Extension into SMD 3.x and update other dependencies in SMUS startup script to successfully bump jupyter-collaboration.  
- [ X ] Image update - New feature
- [ X ] No (New feature or non-critical change)
Manually ran updates to scripts in SMUS env successfully and pending testing in pre start scenario.
- [ X ] My code follows the style …
> Enable Agentic Gen AI extension in 3.x
