- test/test_artifacts/boto3.test.Dockerfile
- test/test_artifacts/keras.test.Dockerfile
- test/test_artifacts/numpy.test.Dockerfile
- test/test_artifacts/pandas.test.Dockerfile
- test/test_artifacts/scipy.test.Dockerfile
- test/test_artifacts/tensorflow.examples.Dockerfile
*Description of changes:* Updated tests to use --freeze-installed flag during micromamba installations
*Testing:* Ran the tests to verify whether the tests are passing successfully with freeze-installed.
> fix: Updated tests to use --freeze-installed flag during micromamba installations

- src/main.py
- template/Dockerfile
- test/test_main.py
…
*Description of changes:* Move Dockerfile to a new template directory and modify the version generator script to copy from that file
Note: 
* I also considered completely removing DockerFiles from the build artifacts folder. But decided against it because this template DockerFile might evolve over time. We should have any easier mechanism to audit the contents of a Dockerfile in a particular image version. Hence left the dockerfile in build artifacts folder.
* Didn't plan on moving gpu.arg_based_env.in. The reason is that : it is a env.in file and I don't expect major changes to that
*Testing:* Unit tests and generated a new patch version locally . Verified that the new patch version had the docker file in it.
By submitting this pull request, I confirm that …
> fix: Move Dockerfile to a new template directory and modify the version generator script to copy from that file

- README.md
- src/config.py
- src/main.py
- src/package_staleness.py
- src/utils.py
- test/test_main.py
- test/test_package_staleness.py
*Description of changes:* Added a script for generating package staleness.
The script generates the report in a Markdown format.
*Testing:* Unit tests + Manual verification for 0.4.1
Ran the following command: 
```
python ./src/package_staleness.py generate-report --target-patch-version 0.4.1
```
And got the following output:
Package | Current Version in the Distribution image | Latest Version in Conda Forge
---|---|---
matplotlib|3.7.2|3.7.2
${\color{red}boto3}$|1.28.20|1.28.22
${\color{red}jupyterlab}$|3.6.5|4.0.4
${\color{red}keras}$|2.12.0|2.13.1
${\color{red}sagemaker-python-sdk}$|2.173.0|2.175.0
${\color{red}ipython}$|8.12.2|8.14.0
pandas|2.0.3|2.0.3
scikit-learn|1.3.0|1.3.0
${\color{red}scipy}$|1.10.1|1.11.1
conda|23.7.2|23.7.2
jinja2|3.1.2|3.1.2 …
> feature: Add a script for generating package staleness

- src/main.py
- src/utils.py
- test/test_main.py
*Description of changes:*  Support generating prerelease versions
* Prevented creation of new major/minor/patch versions from a given prerelease version
* Supported passing a prerelease identifier to create major/minor/patch version artifacts method
* If prerelease identifier is passed, then an additional nested directory will be created inside the regular directory . The name of this new nested directory will be v"major"."minor"."patch"-"prerelease"
* Modified the tag generation logic
* if the given version during the build command is a prerelease version, then just return that version as a tag
* Modified the existing "is_exists_dir_for_version" method to also check whether that directory doesn't just have a prerelease version. This is done by checking whether …
> feature: Support generating prerelease versions

- src/dependency_upgrader.py
- src/main.py
- test/test_dependency_upgrader.py
- test/test_main.py
*Issue #, if available:* https://github.com/aws/sagemaker-distribution/issues/51
During a major version release, I noticed that env.in file has an additional comma in the version constraints. Removed that.
> fix: fix env.in version constraints for major version upgrade

- template/Dockerfile
*Description of changes:* Without this change, the docker image build is not getting completed and it is waiting for user input.
> fix: Installing awscli now requires timezone information.

- src/main.py
- template/Dockerfile
- test/test_main.py
*Description of changes:* Added support for not modifying conda package closure during rebuild.
This is needed for Github action. One Github action might generate the PR for a new version release, but another github action might be responsible for publishing the image. So when the second github action is running, it might fetch the latest versions of python packages. 
This change will prevent that (unless a force argument is passed)
*Testing:*
* unit tests
* verified the behavior with 0.4.0, it didn't modify the env.out files
* ran the same command again with "force" for 0.4.0, it modified the env.out files
> feature: Added support for not modifying conda package closure during rebuild

- src/main.py
- test/test_dockerfile_based_harness.py
* Printed logs during Docker  image build/container run failures
* Deleted test image after the test is ran
*Testing:*
Verified this by testing with an existing image and it printed scipy container logs (after test failures)
> feature: Printed logs for Docker build/run failures

- src/changelog_generator.py
- src/main.py
…
Move change log generation to the build step so that it doesn't depend on image configs.
This will be useful in the future, if we decide to provide arguments to the build command which will only build a particular image type.
> fix: move change log generation to the build step so that it doesn't depend on image configs

- src/main.py
Image config is a nested dictionary. Shallow copy doesn't suffice our requirements. We need to do a deep copy.
> fix: Use deepcopy instead of copy to create the clone of the image config correctly

- pytest.ini
- src/main.py
- test/test_dockerfile_based_harness.py
* Add more flexibility to docker based tests so that we can pass different dockerfiles for different image types
> feature: Add more flexibility to docker based tests so that we can pass different dockerfiles for different image types

- README.md
- src/main.py
- template/Dockerfile
- template/dirs/etc/conda/.condarc
- template/dirs/etc/jupyter/jupyter_server_config.py
- template/dirs/etc/supervisor/conf.d/supervisord.conf
- template/dirs/usr/local/bin/entrypoint-jupyter-server
- template/dirs/usr/local/bin/restart-jupyter-server
- template/dirs/usr/local/bin/start-jupyter-server
* Add default config for Jupyter server
* Add script to start Jupyter server
* Add conda config to install new customer-managed environments under home directory by default
* Add supervisord to manage the Jupyter server process
To start the docker container with Jupyter server running:
```
docker run -p 8888:8888 <image-name> --entrypoint entrypoint-jupyter-server
```
> feature: add Jupyter Server and supervisord config to template

- src/main.py
*Issue #, if available:* None
*Description of changes:* When `--skip-tests` is passed to `src/main.py build`, the resulting images lack names and tags. This results in the fairly obscure output:
```
% docker image ls
REPOSITORY                               TAG                 IMAGE ID       CREATED          SIZE
<none>                                   <none>              30a5081a041d   5 days ago       4.4GB
<none>                                   <none>              0f5ce882b5cd   5 days ago       12.1GB
```
This PR modifies the logic to always name and tag the images regardless of `skip_tests`. The tests are skipped anyways even if the images are named and tagged, so this should be a very safe change.
~~This is targeting the `1.0.0-beta` branch. I can port this to the `main` branch …
> Ensure images are named and tagged even if `skip-tests`

- build_artifacts/v1/v1.0/v1.0.0/v1.0.0-beta/dirs/usr/local/bin/start-jupyter-server
- template/dirs/usr/local/bin/start-jupyter-server
* If SAGEMAKER_APP_TYPE env variable is set, use /<app-type-in-lower-case>/default as the base URI for Jupyter server
* SageMaker will require the base URL of Jupyter server to be set to include app type for the image to be used by SageMaker apps.
* Tested with `docker run -p 8888:8888 --env SAGEMAKER_APP_TYPE=Savitur --entrypoint entrypoint-jupyter-server` and confirmed base URI is correctly set
* Tested with `docker run -p 8888:8888 --entrypoint entrypoint-jupyter-server` and confirmed base URI is not set
> feature: use specific base_url for Jupyter server if SAGEMAKER_APP_TYPE is set

- build_artifacts/v1/v1.0/v1.0.0/v1.0.0-beta/cpu.env.in
- build_artifacts/v1/v1.0/v1.0.0/v1.0.0-beta/gpu.env.in
*Issue #, if available:* None
*Description of changes:* Adds `jupyter-scheduler`.
This PR introduces `jupyter-scheduler` to the image. I've verified the functionality directly by entering the container and recording a demo video of the testing I performed.
https://github.com/aws/sagemaker-distribution/assets/44106031/6c51425f-bba2-4138-ae8d-4bb070149868
Proof that scheduled notebook jobs ("Run on a schedule") work as well:
> Add jupyter-scheduler

- build_artifacts/v1/v1.3/v1.3.0/Dockerfile
- template/Dockerfile
*Issue #, if available:* https://github.com/aws/sagemaker-distribution/issues/137
*Description of changes:* Currently awscli v1 is installed on images, which doesn't have many recent additions including space related apis. This uses [recommended method](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html#getting-started-install-instructions) to install aws cli
> Update awscli to v2

- .github/workflows/build-image.yml
*Description of changes:* CDK created a unique name for testing CodeBuild when it was created. So, updating the name here to match.
> fix: Fix codebuild project name

- src/dependency_upgrader.py
- src/utils.py
- test/test_dependency_upgrader.py
*Issue #, if available:* https://github.com/aws/sagemaker-distribution/issues/177
*Description of changes:* Semver fails with strings like 1.2.3.post1 which are supported by conda-forge, which has led to problems. If there are > 2 periods, we get first 3 entries only.
> fix: Fix version parsing for pre/post releases

- src/main.py
- src/utils.py
- test/test_main.py
*Description of changes:* Currently when creating new version, we always get the Dockerfile/dirs from the template folder. However, with new packages being added in minor versions, we want to keep patches with the same Dockerfile/dirs which they were created with. So for patches, get Dockerfile/dirs from previous patch.
Also, update conda import to match new path (https://github.com/conda/conda/pull/13168)
> feature: Get static files from previous patch.

- README.md
- template/v0/Dockerfile
- template/v1/Dockerfile
*Issue #, if available:*  https://github.com/aws/sagemaker-distribution/issues/161
*Description of changes:* 
Adding OpenSSL FIPS provider. We will install OpenSSL using conda-forge to ensure compatibility with all packages, however the latest FIPS-verified provider is from OpenSSL 3.0.8. Followed [these instructions](https://github.com/openssl/openssl/blob/master/README-FIPS.md#installing-the-fips-provider-and-using-it-with-the-latest-release) for installing FIPS-verified provider on top of existing OpenSSL installation, which involves fetching source code for both installed and verified versions, testing the verified providers against the installed version, then installing just the FIPS provider from 3.0.8. 
For testing, build new v0 and v1 image and ran following commands on cpu and …
> feature: Add OpenSSL FIPS provider

- build_artifacts/v1/v1.6/v1.6.0/CHANGELOG-cpu.md
- build_artifacts/v1/v1.6/v1.6.0/CHANGELOG-gpu.md
- build_artifacts/v1/v1.6/v1.6.0/Dockerfile
- build_artifacts/v1/v1.6/v1.6.0/RELEASE.md
- build_artifacts/v1/v1.6/v1.6.0/cpu.env.in
- build_artifacts/v1/v1.6/v1.6.0/cpu.env.out
- build_artifacts/v1/v1.6/v1.6.0/dirs/etc/code-editor/code_editor_machine_settings.json
- build_artifacts/v1/v1.6/v1.6.0/dirs/etc/code-editor/extensions.txt
- build_artifacts/v1/v1.6/v1.6.0/dirs/etc/supervisor/conf.d/supervisord-code-editor.conf
- build_artifacts/v1/v1.6/v1.6.0/dirs/etc/supervisor/conf.d/supervisord-common.conf
- build_artifacts/v1/v1.6/v1.6.0/dirs/etc/supervisor/conf.d/supervisord-jupyter-lab.conf
- build_artifacts/v1/v1.6/v1.6.0/dirs/usr/local/bin/entrypoint-code-editor
- build_artifacts/v1/v1.6/v1.6.0/dirs/usr/local/bin/start-code-editor
- build_artifacts/v1/v1.6/v1.6.0/gpu.env.in
- build_artifacts/v1/v1.6/v1.6.0/gpu.env.out
*Description of changes:* Previous release PR didn't have sagemaker-code-editor. Adding that in here and rebuilding
> fix: Fix 1.6.0 release artifacts

- src/main.py
*Description of changes:* Currently, if --target-ecr-repo is specified, and --skip-tests is _not_ specified, we would only push to ECR if all tests pass for both image variants. With the current state of our test suites, this doesn't happen. This means that we need to build an image and run tests, then push the image in a separate build (or do some local tag manipulation). This means, if we do two build commands, the image which is pushed could be different than the image which was tested.
In our current manual/automated build process, we run the tests and push to private, and separately push to public after the release PR is merged. In this case, we want to push to private the image which is tested, then be able to push to public the exact image which was tested. …
> change: Push to ECR before running tests

- test/test_artifacts/v1/keras.test.Dockerfile
- test/test_artifacts/v1/pytorch.examples.Dockerfile
- test/test_artifacts/v1/scripts/run_autogluon_tests.sh
- test/test_artifacts/v1/sm-python-sdk.test.Dockerfile
- test/test_dockerfile_based_harness.py
*Description of changes:* Bunch of fixes to support testing on codebuild. Fixes failures for:
* keras - failed with cuda errors due to installing incompatible cuda-nvcc. Adding version constraints fixes this.
* pytorch - failed with `libcuda.so: cannot open shared object file: No such file or directory`. Adding a link between libcuda.so.1 to libcuda.so resolves. This is also done in codebuild, but must not carry over into the test dockerfile
* autogluon - saw errors that shmsize was not sufficient. Increasing from default 64mb to 256mb resolves. Also, since there are ~5 pkgs containing autogluon, the version fetching line wasn't working. Updated to pull version correctly.
Additional failures
* sm-python-sdk - saw failures for 3 tests. 2 related to not having …
> fix: Fixes for automated testing

- .github/workflows/build-image.yml
- src/main.py
Currently if tests fail against one variant, e.g. gpu, tests won't run against others. This change updates to run on all variants and return exit codes at the end. 
Also update to use 2 workers as we see resource issues with more, and update codebuild role timeout to actually be 8 hours.
> fix: Improvements for testing

- test/test_dockerfile_based_harness.py
*Description of changes:* Still seeing occasional errors with autogluon test `ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).` ([e.g.](https://cosmosrelease-githubcodebuildlogssar-1u1-buildlogs-io1ptro4snwc.s3.amazonaws.com/2d21d251-af85-4cd3-a353-b232ae56ed5b/build.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIA2GLMOUUQZ4MZZVQR%2F20240325%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240325T155133Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEHgaCXVzLWVhc3QtMSJGMEQCIAvowSE%2BIy8uxDaW3e4HnHRe4VI03qwqFr2HXBlfXFdqAiBgfFKKgQsm0AK7lTBXmgivl780yb8u9PF9NNZfMvyk8CrcAwiR%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAAaDDcwMDg0Mzk5MjM1MyIMNB6LKSI5k0sUa7jXKrAD%2F7%2Fs5tZvupE%2BwEfHq …
> fix: Increase shm_size for tests

- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/cpu.additional_packages_env.in
- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/gpu.additional_packages_env.in
- test/test_artifacts/v2/git-remote-codecommit.test.Dockerfile
- test/test_artifacts/v2/scripts/run_git_remote_codecommit_test.sh
- test/test_dockerfile_based_harness.py
Test:
- Build image locally and goes into the docker container and verified installation via conda list
- Added test case and verified by: pytest -m gpu --local-image-version 2.0.0-beta -k  git-remote-codecommit pytest -m cpu --local-image-version 2.0.0-beta -k  git-remote-codecommit
Add git-remote-codecommit to SMD
> Add git-remote-codecommit to SMD

- template/v1/dirs/etc/jupyter/jupyter_server_config.py
Set the LanguageServerManager.extra_node_roots setting if amazon_sagemaker_sql_editor exists in the environment. Ignore otherwise, don't fail the JL server start.
Related documentation: https://jupyterlab-lsp.readthedocs.io/en/v3.4.0/Configuring.html
1. The new version of `amazon-sagemaker-sql-editor` is packaging `sql-language-server` in it at the path {module-root}/sql-language-server.
2. In this change we are telling LanguageServerManager to look into {module-root}/sql-language-server (if it is found, silently ignore error otherwise) via a jupyter config. This config tells where would LanguageServerManager look for servers and is isolated to the LSP feature.
Testing:
1. Created a custom image with the following Dockerfile
```
FROM …
```
> Add sql-language-server config for LanguageServerManager

- .github/workflows/monthly-minor-release.yml
- .github/workflows/nightly-build-image.yml
- .github/workflows/weekly-patch-release.yml
*Description of changes:* 
* Only generate patches for v1
* Rename nightly build so it's different from regular build
* Pass secrets when calling build workflow- github token isn't getting passed leading to failed aws authentication for scheduled calls
> fix: Fixes for automation

- template/v1/Dockerfile
`amazon_sagemaker_sql_editor` extension creates and stores cache files for autocompletion capability under `/home/sagemaker` directory. To avoid exposing customers to such internal working files, we create `/opt/amazon/sagemaker/user-data` which extensions can use to store files.
Create a dir `/opt/amazon/sagemaker/user-data` in which `amazon_sagemaker_sql_editor` extension can create and store files for use.
*Testing*
1. Created a custom image with the following Dockerfile
```
FROM public.ecr.aws/sagemaker/sagemaker-distribution:latest-cpu
ARG NB_USER="sagemaker-user"
ARG NB_UID=1000
ARG NB_GID=100
ENV MAMBA_USER=$NB_USER
USER root
RUN mkdir -p /opt/amazon/sagemaker/sagemaker-sql-experience-user-data \
&& chown $MAMBA_USER:$MAMBA_USER …
```
> create dir to store user data files

- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/etc/maxdome/kernels/kernel_launchers/glue_kernel_launcher.sh
- build_artifacts/v2/v2.0/v2.0.0/v2.0.0-beta/dirs/usr/local/bin/start-maxdome-jupyter-server
- template/v2/dirs/etc/maxdome/kernels/kernel_launchers/glue_kernel_launcher.sh
- template/v2/dirs/usr/local/bin/start-maxdome-jupyter-server
During tests we noticed there will be error in restarting jupyter, because the script will error out as the kernel is already removed.
In this change, we will only remove the kernel when it is present.
We also removed glue_role_arn in kernel launcher script for glue.
Test:
Verify JupyterLab will auto restart when it is killed
> Only remove kernel when installed

- src/main.py
- test/test_main.py
*Issue #, if available:*N/A
*Description of changes:*  Add versioning support for images with prerelease identifiers
Motivation:
* Currently we don't allow creating new {major/minor/patch} versions from a prerelease version.
What is changing:
Current behavior: if you invoke create-{major/minor/patch}-version-artifacts for a prerelease version (like 1.0.0-beta) you will get an exception.
New behavior: These invocations will succeed and it will create 3.0.0-beta/2.1.0-beta/2.0.1-beta respectively.
> feature: Add versioning support for images with prerelease identifiers

- .github/workflows/monthly-minor-release.yml
- .github/workflows/weekly-patch-release.yml
*Description of changes:* Disabling scheduled releases for now; creating a lot of noise/infra stress for releases which we end up restarting anyways. Will re-enable once E2E release cadence has stabilized
> change: Disable scheduled releases

- template/v1/dirs/etc/jupyter/jupyter_server_config.py
Make amazon q default language model for JupyterAI
Take a look at JupyterAI [docs](https://jupyter-ai.readthedocs.io/en/latest/users/index.html#configuration) about configurations for more info
> Make amazon q default language model

- build_artifacts/v1/v1.9/v1.9.0/cpu.additional_packages_env.in
- build_artifacts/v1/v1.9/v1.9.0/gpu.additional_packages_env.in
- test/test_artifacts/v2/amazon-q-developer-jupyterlab-ext.test.Dockerfile
- test/test_artifacts/v2/amazon-sagemaker-jupyter-ai-q-developer.test.Dockerfile
Add amazon-sagemaker-jupyter-ai-q-developer and others amazon-q-developer-jupyterlab-ext.
Adding new dependencies and bumping others as follows:
1.    amazon-sagemaker-jupyter-ai-q-developer[version='>=1.0.3,<2.0'] - new extension
2.    amazon-q-developer-jupyterlab-ext[version='>=3.1.0,<4.0'] - new extension for CW
> feature: Add amazon-sagemaker-jupyter-ai-q-developer and others

- build_artifacts/v2/v2.0/v2.0.0/cpu.additional_packages_env.in
- build_artifacts/v2/v2.0/v2.0.0/gpu.additional_packages_env.in
- test/test_artifacts/v2/sagemaker-mlflow.test.Dockerfile
- test/test_artifacts/v2/scripts/run_mlflow_tests.sh
- test/test_artifacts/v2/scripts/run_sagemaker_mlflow_tests.sh
- test/test_dockerfile_based_harness.py
Add the sagemaker-mlflow package from conda-forge
*Test results:*
```
python -m pytest -n auto -m cpu -vv -rs -k "sagemaker-mlflow" --local-image-version $VERSION                                                                                    ──(Thu,Jun20)─┘
============================================================================================================== test session starts ==============================================================================================================
platform linux -- Python 3.12.3, pytest-8.2.2, pluggy-1.5.0 -- /home/saimidu/miniconda3/envs/sagemaker-distribution/bin/python
cachedir: .pytest_cache
rootdir: /local/home/saimidu/sagemaker-distribution
configfile: pytest.ini
plugins: …
```
> feature: Add sagemaker-mlflow package

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/PR_TEMPLATE.md
- src/changelog_generator.py
- src/main.py
- src/package_report.py
- src/utils.py
- test/test_main.py
- test/test_package_report.py
Add a tool for generating package dependency report for newly introduced packages in an image. It will provide a full list of dependencies and required versions for new marquee packages in the image release.
> Add a tool for generating package dependency report

- template/v0/Dockerfile
- template/v1/Dockerfile
- template/v2/Dockerfile
*Description of changes:* Previously we pull openssl source code from openssl.org, as part of installing FIPS provider and testing. It seems with newer versions they've stopped publishing here, but all versions are available on github.com. This was blocking 1.10.1 build, and this change unblocked. Confirmed FIPS module is still working.
Note: Future patch releases will run into this failure. We don't want to edit the already released images' dockerfiles, so we'll need to update each patch's Dockerfile as we release.
> fix: Update openssl source code url

- src/main.py
- template/v0/Dockerfile
- template/v1/Dockerfile
- template/v2/Dockerfile
- test/test_main.py
…
*Description of changes:* As titled
*Testing:* Tested by creating a new 0.14 cpu image and verified that it has the new environment variable
> feature: Support maintaining an environment variable containing the image version

- test/test_artifacts/v2/run_pandas_tests.py
*Issue #, if available:* https://github.com/aws/sagemaker-distribution/issues/110
*Description of changes:* Fix failed Pandas tests
Latest failures in 2.x images:
```
FAILED pandas/tests/indexes/object/test_indexing.py::TestSliceLocs::test_slice_locs_negative_step[in_slice13--string[pyarrow_numpy]]
FAILED pandas/tests/plotting/frame/test_frame.py::TestDataFramePlots::test_plot_scatter_shape
FAILED pandas/tests/plotting/test_datetimelike.py::TestTSPlot::test_mpl_nopandas
ERROR pandas/tests/io/test_clipboard.py::TestClipboard::test_round_trip_frame_sep[delims-None-None]
ERROR pandas/tests/io/test_clipboard.py::TestClipboard::test_round_trip_frame_sep[delims-None-\t]
ERROR pandas/tests/io/test_clipboard.py::TestClipboard::test_round_trip_frame_sep[delims-None-,]
ERROR …
```
> Fix failed Pandas tests

- template/v1/Dockerfile
- template/v1/dirs/etc/code-editor/code_editor_user_settings.json
- template/v2/Dockerfile
- template/v2/dirs/etc/code-editor/code_editor_user_settings.json
- test/test_artifacts/v1/scripts/run_sagemaker_code_editor_tests.sh
- test/test_artifacts/v2/scripts/run_sagemaker_code_editor_tests.sh
Disable auto update for CodeEditor extensions
> Disable auto update for CodeEditor extensions

- template/v2/dirs/etc/code-editor/extensions.txt
- template/v3/dirs/etc/code-editor/extensions.txt
- Add Amazon Q Code Editor extension v1.32.0 - https://open-vsx.org/extension/amazonwebservices/amazon-q-vscode
- Update AWS Toolkit Code Editor extension to v3.30.0 - https://open-vsx.org/extension/amazonwebservices/aws-toolkit-vscode
> add amazon q and update aws toolkit code editor extensions

- build_artifacts/v3/v3.0/v3.0.0/cpu.additional_packages_env.in
- build_artifacts/v3/v3.0/v3.0.0/gpu.additional_packages_env.in
- test/test_artifacts/v2/docker-cli.test.Dockerfile
- test/test_artifacts/v2/scripts/run_docker_cli_tests.sh
- test/test_dockerfile_based_harness.py
- Added the package to the {cpu/gpu}.additional_packages_env.in files
- Added import test for the jupyter-activity-monitor-extension extension package
- Built the images successfully and tested on the image. Results were as expected.
conda-forge: https://anaconda.org/conda-forge/docker-cli
Test results:
```
dev-dsk-cindyxl-2a-78c20928 % python -m pytest -n auto -m cpu -vv -rs -k "docker-cli" --local-image-version 2.1.0           
======================================================= test session starts =======================================================
platform linux -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0 -- /home/cindyxl/anaconda3/envs/sagemaker-distribution/bin/python
cachedir: .pytest_cache
rootdir: …
```
> feat:Add docker cli to SMD 3.0.0

- build_artifacts/v2/v2.2/v2.2.0/cpu.additional_packages_env.in
- build_artifacts/v2/v2.2/v2.2.0/gpu.additional_packages_env.in
- test/test_artifacts/v2/docker-cli.test.Dockerfile
- test/test_artifacts/v2/scripts/run_docker_cli_tests.sh
- test/test_dockerfile_based_harness.py
- Added the package to the {cpu/gpu}.additional_packages_env.in files
- Added import test for the jupyter-activity-monitor-extension extension package
- Built the images successfully and tested on the image. Results were as expected.
conda-forge: https://anaconda.org/conda-forge/docker-cli
Test results:
```
dev-dsk-cindyxl-2a-78c20928 % python -m pytest -n auto -m cpu -vv -rs -k "docker-cli" --local-image-version 2.1.0           
======================================================= test session starts =======================================================
platform linux -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0 -- /home/cindyxl/anaconda3/envs/sagemaker-distribution/bin/python
cachedir: .pytest_cache
rootdir: …
```
> feat:Add docker cli to SMD

- test/test_artifacts/v2/scripts/run_pysdk_tests.sh
*Issue #, if available:* https://github.com/aws/sagemaker-distribution/issues/316
Skipped those test cases which needs credentials, or Docker daemon as it cannot be provided in SMD image as of now.
> Fixed UT run_pysdk_tests.sh

- test/test_artifacts/v0/scripts/run_autogluon_tests.sh
- test/test_artifacts/v1/scripts/run_autogluon_tests.sh
- test/test_artifacts/v2/scripts/run_autogluon_tests.sh
Added comment in autogluon test case script regarding  failure of in multi-GPU env as  multimodal-quick-start.ipynb supports single GPU env. It fails/gives unexpected error in Multi-GPU env due DDP(Distributed Data Parallel) while running training phase.
> Added comment in autogluon test script.

- .gitignore
- template/v0/Dockerfile
- template/v1/Dockerfile
- template/v2/Dockerfile
- template/v3/Dockerfile
*Issue #, if available:* 
App cannot start if there is corrupted condarc file
https://t.corp.amazon.com/P162071398/information
*Motivation*
Upgrade mircromamba version to include the open source fix in 1.5.11 
Also jammy image tag is effective deprecated https://github.com/mamba-org/micromamba-docker/issues/573#issuecomment-2563138910
source: https://github.com/mamba-org/mamba/pull/3580
- Added logic to compare the current micromamba version with a configurable minimum required version (MIN_REQUIRED_MICROMAMBA_VERSION, default: 1.5.11).
- Automatically upgrades micromamba if the installed version is strictly lower than the required version.
- Prevents unnecessary updates or downgrades if the current version already satisfies the requirement.
- Introduced ARG …
> feat: Ensure micromamba meets minimum required version during build

- .github/workflows/check-image-size.yml
- src/main.py
- src/package_report.py
*Changes Made:*
- Updated `package_report.py` to handle staging repository and account information as command-line arguments.
- Modified the argument parser in `main.py` to require `--staging-repo-name` and `--staging-account` for the `generate-size-report` command.
- Updated the GitHub Actions workflow (`check-image-size.yml`) to pass these new required parameters.
- The `generate-size-report` command now requires `--staging-repo-name` and `--staging-account` arguments.
- These values are passed through to the `get_image_size` function in `package_report.py`.
- The GitHub Actions workflow has been updated to provide these values when Codebuild job will be triggered.
*Run the script with:*
```bash
python ./src/main.py generate-size-report …
```
> Fix generate image size report

- template/v2/Dockerfile
- template/v2/dirs/usr/local/bin/entrypoint-jupyter-server
- template/v2/dirs/usr/local/bin/start-jupyter-server
- test/test_dockerfile_based_harness.py
- Fix the home directory env variable
- add supervisord as the dependency for recovery-mode micromamba env
> fix: recovery mode home path

- template/v2/dirs/etc/supervisor/conf.d/supervisord-code-editor.conf
- template/v2/dirs/usr/local/bin/merge-settings-util.py
- template/v2/dirs/usr/local/bin/start-code-editor
n/a
Persisting CodeEditor settings across app restarts. Settings are now stored in the EBS volume. 
*Testing*
Built the image and tested manually as a custom image. 
Changed some settings, then stopped the space and re-started in a new browser to ensure they were persisted.
Also added some dummy default settings and mutated them in the app, then restarted the space and made sure they were reset back to defaults.
> Persisting CodeEditor settings across app restarts

- src/utils.py
- template/v3/Dockerfile
- template/v3/dirs/etc/sagemaker-inference-server/__init__.py
- template/v3/dirs/etc/sagemaker-inference-server/serve
- template/v3/dirs/etc/sagemaker-inference-server/serve.py
- template/v3/dirs/etc/sagemaker-inference-server/tornado_server/__init__.py
- template/v3/dirs/etc/sagemaker-inference-server/tornado_server/async_handler.py
- template/v3/dirs/etc/sagemaker-inference-server/tornado_server/server.py
- template/v3/dirs/etc/sagemaker-inference-server/tornado_server/stream_handler.py
- template/v3/dirs/etc/sagemaker-inference-server/tornado_server/sync_handler.py
- template/v3/dirs/etc/sagemaker-inference-server/utils/__init__.py
- template/v3/dirs/etc/sagemaker-inference-server/utils/environment.py
- template/v3/dirs/etc/sagemaker-inference-server/utils/exception.py
- template/v3/dirs/etc/sagemaker-inference-server/utils/logger.py
Added source code to enable serving capabilities on SageMaker Endpoint.
- when the serve command is passed on container startup, the inference server script will execute
- it will then start a Tornado web server in either async or sync mode
*Testing*
Using a basic LCEL inference script:
```
logger = logging.getLogger("sagemaker_distribution.inference_server")
qa_prompt = ChatPromptTemplate.from_template("{question}")
bedrock_runtime = boto3.client(
service_name="bedrock-runtime"
)
text_gen_model = Bedrock(
model_id="anthropic.claude-v2",
client=bedrock_runtime
)
text_gen_model.guardrails.update(
{
"guardrailVersion": None,
"guardrailIdentifier": None,
}
)
lcel_chain = qa_prompt | text_gen_model
def handler(request):
return lcel_chain.stream(request.body)
```
- …
> feat: Enable inference serving capabilities on sagemaker endpoint

- support_policy.md
Moved 1.10, 1.11, and 2.0 to Unsupported table.
1.10 is past EOS date, 2.0 is past EOS date. 
1.11 has not been able to be patched since 1/8 due to CVEs and should be added to the unsupported table with a date update
> Move 1.10, 1.11, and 2.0 to Unsupported table

- src/utils.py
Seeing `PackagesNotFoundError` blocking package size report generation, it happens when packages like https://anaconda.org/conda-forge/fmt/files have most of versions marked as `broken`.
Ignore such package and continue to check remaining ones in such case.
> Swallow PackagesNotFoundError when generating size report

- .github/workflows/validate-image.yml
Add PR validation to validate image github action:
- Require an input PR number
- validate that the PR number:
- Maps to a PR that has the correct title
- Check that the PR is NOT from a forked repository.
> Add PR validation to validate image github action

- template/v2/dirs/etc/code-editor/extensions.txt
- template/v3/dirs/etc/code-editor/extensions.txt
Update the Q chat version for CodeEditor to 1.58.0. Locally tested in SM AI and SMUS.
> Update the Q chat version for CodeEditor to 1.58.0

- template/v2/dirs/etc/sagemaker-ui/kernels/kernel_launchers/python3_kernel_launcher.sh
In this commit we:
(1) ensure that we respect $SPARKMAGIC_CONF_DIR if set by user (2) if invoked from workflow and $SPARKMAGIC_CONF_DIR is not set, we set it to be the value of $SM_EXECUTION_INPUT_PATH
Test:
modify the script on space, set env vars of $SM_EXECUTION_INPUT_PATH and $SPARKMAGIC_CONF_DIR.
> Fix issue of SparkMagic config file not accessible in workflow

- template/v2/dirs/etc/sagemaker-ui/git_clone.sh
- template/v2/dirs/etc/sagemaker-ui/git_config.sh
This PR moves the commands to configure the git credential helper into its own file, separate from the `git_clone.sh` script, to fix workflows functionality in SageMaker Unified Studio (SMUS) projects with third-party repositories.
At the end of this line:
`git config --global credential.helper "!aws --profile DomainExecutionRoleCreds --region $dataZoneDomainRegion codecommit credential-helper --ignore-host-check $@"`
we pass in `$@`, which represents all command-line arguments passed to a script or command. CodeCommit requires this in the credential helper ([ref](https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-https-unixes.html#setting-up-https-unixes-credential-helper)).
If the `git_clone.sh` script is invoked with a parameter, the above line …
> fix(GitClone): Fix git clone script to set the credential helper without passing args from the script invocation

- environment.yml
- src/package_report.py
Adds download statistics to staleness report to gauge package popularity. Also sorting alphabetically, such that stale packages are on top and it's easier to find specific package.
Code quality check is failing for some template/test files, should fix in separate PR
---
Example staleness report
Package | Current Version in the Distribution image | Latest Relevant Version in Upstream | Downloads (Conda, previous month)
---|---|---|---
${\color{red}boto3}$|1.36.23|1.36.26|761137
${\color{red}uvicorn}$|0.34.0|0.34.2|213369
${\color{red}langchain}$|0.3.23|0.3.24|36371
${\color{red}amazon-q-developer-jupyterlab-ext}$|3.4.7|3.4.8|3199
${\color{red}amazon-sagemaker-jupyter-ai-q-developer}$|1.0.16|1.0.17|3077 …
> Add download stats to staleness report

- src/package_report.py
Fetching the download data in report from the month before last. At the beginning of the month, the conda download data for the last month may not be ready. The report generation will fail if this happens.
> Fetching the download data in report from the month before last

- template/v2/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
**Description**
When a call fails to get-domain-execution-role-credential-in-space, the call will hang indefinitely. This PR adds a timeout to the call to ensure failures are returned.
Also, this PR fixes an issue in JL spaces where a space with 2 or fewer CPU cores
**Testing Done**
1. Installed latest maxdome data science extensions package
2. Loaded two tabs running the same space
3. In one tab, refresh the page
4. in the other tab , run sagemaker_ui_post_startup.sh
5. Confirm both success and error cases work as expected.
> post startup script: Add timeout to get domain exec role creds call to prevent hanging

- template/v3/Dockerfile
- template/v3/dirs/usr/local/bin/entrypoint-jupyter-server
- template/v3/dirs/usr/local/bin/start-jupyter-server
*Description of changes:* Updating sagemaker-recovery-mode path from  `/home/sagemaker-user/.conda/envs/sagemaker-recovery-mode` to `/opt/conda/envs/sagemaker-recovery-mode`. Seen some issues in SM AI Studio with the former path, fixed using new path. Tested in SM AI Studio.
> Update sagemaker-recovery-mode path

- support_policy.md
- update support policy, update date for 1.12, 1.13, 2.2 and 2.3
- move 2.1 to 2.3 to Unsupported Image Versions table
> update support policy

- support_policy.md
Update EOS date for 2.4.x to May 25th, 2025. It has CVE cannot be patched within minor version, and we've released SMD 2.6.0 patching that CVE.
> Update EOS date for 2.4.x

- test/test_artifacts/v2/sagemaker_studio_dataengineering_extensions.test.Dockerfile
- test/test_artifacts/v2/scripts/run_sagemaker_studio_dataengineering_extensions_test.sh
Remove running the unit test, because the tests are not built into pypi and conda to minimize the size.
Function tests are covered by integ test/canary.
> Update sagemaker_studio_dataengineering_extensions tests

- src/main.py
- src/package_report.py
Add a flag controlling if we should show download stats in staleness report. The image build job is consistently failing due to failure when getting package download counts. Change the default behavior to not getting the download stats.
Tested locally by generating a report
> Add a flag controlling if we should show download stats in staleness report

- test/test_artifacts/v2/anaconda.test.Dockerfile
- test/test_artifacts/v2/scripts/run_anaconda_tests.sh
- test/test_artifacts/v3/anaconda.test.Dockerfile
- test/test_artifacts/v3/scripts/run_anaconda_tests.sh
- test/test_dockerfile_based_harness.py
*Description of changes:* Adds a test to confirm only conda-forge channel is being used from anaconda. 
Ran test against v2 and v3:
```
======================================================================================================= PASSES =======================================================================================================
_______________________________________________________________________ test_dockerfiles_for_cpu[anaconda.test.Dockerfile-required_packages0] ________________________________________________________________________
------------------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------------- …
```
> Add test for validating anaconda channels

- .github/workflows/build-image.yml
*Description of changes:* We need to set fetch-depth to get all branches; in 2.6.1 build, it found existing branch, but then failed to check it out. https://github.com/actions/checkout?tab=readme-ov-file#fetch-all-history-for-all-tags-and-branches
```
277453eef5b4476844bec5e0894ffa73fc9165e8	refs/heads/release-2.6.1
Branch exists, merging latest changes in
error: pathspec 'release-2.6.1' did not match any file(s) known to git
```
> Set fetch-depth to get all branches in image build

- template/v2/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
- template/v3/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
This change modifies the post startup script to not initialize a Git repository and skip creating the `~/src` directory if the project uses the non-git storage feature. Shared storage for the project will be provided via a S3 bucket mounted on the space. 
N/A - Patch is not required
Tested the changes in 3 different projects by running the post startup script from a terminal window
1) CodeConnections (3P Git)
- Verified that src dir is created and git …
> Updating post startup script for non-git storage feature

- template/v2/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
- template/v3/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
The long term fix has been addressed in backend so removing this override logic from post startup script to enable the jupyter_ai slash commends
- Image update - Bug fix
- Yes (Critical bug fix or security update)
The newest jupyter_ai extension has been included in the current baking patch version and we observed the issue which config file is overridden. So yes this has to be included in. 
Triggered the script manually and the config file wasn't changed …
> Remove Jupyter_AI config override from post script

- template/v2/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
- template/v3/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
In #719, SMUS_PROJECT_DIR was exported to be used as the source of truth for where the projects contents would be available, however since the post startup script happens after JupyterLab is started, extensions in JL are unable to pick up this var. This change writes the value of SMUS_PROJECT_DIR to a JSON file in 
`$HOME/.config/smus-storage-metadata.json`
N/A - does not need to be patched into previous …
> Writing SMUS_PROJECT_DIR to a JSON file to be accessed by JupyterLab Extensions

- template/v2/dirs/etc/sagemaker-ui/network_validation.sh
- template/v2/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
- template/v3/dirs/etc/sagemaker-ui/network_validation.sh
- template/v3/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
**Description**
This change introduces the network validation script which tests if certain AWS services are reachable by making read only API calls with a set timeout. If the call exceeds the timeout, the script infers that it was caused by a bad network setup such as not having access to the internet/ VPC endpoint to make the call. API calls that resolve (succeed or fail) within the timeout are inferred as having the proper network setup.
AWS services for Compute Connections and Git are checked in this script. More specifically, the script lists the datazone connections to see which services need to be checked.
The unreachable services are aggregated and are displayed by writing to the post-startup-status.json, which displays the error notification in the IDE.
**Testing**
Tested in a …
> Add network validation script executed in the sagemaker_ui_post_startup script

- template/v2/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
- template/v3/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
followup on https://github.com/aws/sagemaker-distribution/pull/729/files, also add the IS_GIT_PROJECT flag to env variable and write to .config/smus-storage-metadata.json  so that it can be used in Jupyterlab extensions
tested by running the touched lines in Gamma jupyterlab: 
```
sagemaker-user@default:~/.config$ is_s3_storage_flag=1
sagemaker-user@default:~/.config$ …
```
> Add IS_GIT_PROJECT variable and write to smus-storage-metadata.json

- template/v2/dirs/usr/local/bin/entrypoint-sagemaker-ui-jupyter-server
- template/v2/dirs/usr/local/bin/start-sagemaker-ui-jupyter-server
- template/v3/dirs/usr/local/bin/entrypoint-sagemaker-ui-jupyter-server
- template/v3/dirs/usr/local/bin/start-sagemaker-ui-jupyter-server
In both version 2 and 3
In Entrypoint scripts:
-Created a new folder which will be used as home directory in recovery mode
-Added if condition to start switch micromamba environment based on recovery mode
In Start scripts:
-Added if condition to start switch micromamba environment based on recovery mode
-Added if condition to disable collaboration and identity_provider_class flags to be able to provide minimal environment for recovery mode
- Image update - New feature
- New feature
I ran the script using a custom image, passing in the recovery mode parameter set to both true and false via the API call. I then tested the script on the SMUS platform and observed that Jupyterlab started as intended in both scenarios
> feat: Add recovery mode support for Unified Studio

- template/v2/dirs/etc/sagemaker-ui/network_validation.sh
- template/v2/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
- template/v3/dirs/etc/sagemaker-ui/network_validation.sh
- template/v3/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
If a user has access to the internet, but does not have a VPC Endpoint attached to their network, API calls made within the network_validation script may fail due to "Could not connect to the endpoint URL". This change ensures these errors are caught and surfaced to the user.
- [] Yes (Critical bug fix or security update)
Tested in a SMUS portal containing internet, …
> Update network_validation script to flag failing calls due to endpoint URL as unreachable

- template/v2/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
- template/v3/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
Determine if a Domain is is in Express Mode  and configure DomainExecutionRoleCreds profile accordingly.
To determine a if domain is a is in Express Mode, we make a GetDomain API call with `--debug` since the DOMAIN_MODE field is not public right now.
This is needed because domains in Express mode do not have a DomainExecutionRole and hence the post startup script fails with AccessDeniedException.
[Explain the criticality of this change and why it should …
> Determine if a Domain is in Express Mode and configure DER creds profile

- template/v2/dirs/etc/sagemaker-ui/sagemaker-mcp/default.json
- template/v2/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
- template/v3/dirs/etc/sagemaker-ui/sagemaker-mcp/default.json
- template/v3/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
- Add default.json configuration files for Amazon Q agents in v2 and v3 templates
- Add migration logic in post-startup scripts to merge MCP configurations
- Support intelligent merging of existing agent configurations
Due to some dependencies logic changes the agentic chat mcp configuration file location changed. This PR is adding a migration logic when space run the post startup script.
Yes, tested the …
> feat: add Amazon Q agent configuration and MCP migration

- template/v2/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
- template/v2/dirs/usr/local/bin/entrypoint-sagemaker-ui-code-editor
- template/v2/dirs/usr/local/bin/entrypoint-sagemaker-ui-jupyter-server
- template/v3/dirs/etc/sagemaker-ui/sagemaker_ui_post_startup.sh
- template/v3/dirs/usr/local/bin/entrypoint-sagemaker-ui-code-editor
- template/v3/dirs/usr/local/bin/entrypoint-sagemaker-ui-jupyter-server
This change moves the Q CLI telemetry setup to the post-startup script, adds domain mode handling for the Q CLI telemetry, and tracks the domain mode in an environment variable using the `.bashrc` file.
To make sure we capture accurate environment telemetry, we need this change in SMD v2.9 and v3.4 patch versions.
I built the image locally following the contribution guide and used BYOI to test the script changes in SageMaker Unified Studio. I made sure …
> Move Q CLI telemetry and add domain mode to post-startup script

- template/v2/Dockerfile
- template/v3/Dockerfile
Delete useless artifacts from final image:
- Files: .../yarn.lock
Because SMD doesn't use `yarn` or `npm` to install any dependency, neither require `yarn` or `npm` usage during runtime for any SMD specific functionality (through users have the ability to do whatever they want inside the container)
1. Build 3.4.0 CPU and GPU images locally
2. Run unit tests against …
> Delete useless artifacts from final image

- template/v2/dirs/usr/local/bin/start-sagemaker-ui-jupyter-server
Add SQLiteYStore and ArbitraryFileIdManager database paths to start-sagemaker-ui-jupyter-server script to v2 template
**Description**
This changes adds SQLiteYStore and ArbitraryFileIdManager database paths to start-sagemaker-ui-jupyter-server script in order to fix the SQLLite read only error causing files to not open in SMD 2.9 with jupyter-collaboration. This change adds these paths to v2 template
[Explain …
> Add SQLiteYStore and ArbitraryFileIdManager database paths to start-sagemaker-ui-jupyter-server script to v2 template

- build_artifacts/v2/v2.10/v2.10.0/cpu.additional_packages_env.in
- build_artifacts/v2/v2.10/v2.10.0/gpu.additional_packages_env.in
- build_artifacts/v3/v3.5/v3.5.0/cpu.additional_packages_env.in
- build_artifacts/v3/v3.5/v3.5.0/gpu.additional_packages_env.in
- test/test_artifacts/v2/scripts/run_strands_tests.sh
- test/test_artifacts/v2/strands.test.Dockerfile
- test/test_artifacts/v3/scripts/run_strands_tests.sh
- test/test_artifacts/v3/strands.test.Dockerfile
- test/test_dockerfile_based_harness.py
We want to add Strands-agents, strands-agents-tools and strands-agents-mcp-server packages to SMD 2.10 and 3.5.
- [x ] Image update - New feature
- [ x] No (New feature or non-critical change)
I created tests to import all the packages required and checked if the succeeded. you can find more info in the strands.test file
- [x ] My code …
> Add Strands to SMD 2.10 and 3.4

- .github/workflows/build-image.yml
Add --author 'app/github-actions' flag to gh pr list command to prevent attackers from creating malicious PRs with matching head branch names that could be selected by the workflow instead of trusted bot-created PRs.
This prevents remote code execution via malicious PR injection during the release process.
[Describe the …
> fix race condition vulnerability in build-image workflow

- template/v3/dirs/usr/local/bin/start-code-editor
This PR adds changes needed to support recovery mode for CodeEditor. 
In recovery mode, we need to not utilizing the standard mode home directory `/home/sagemaker-user`
This PR updates it to use temp clean folders `/tmp/sagemaker-recovery-mode-home` and does not include any settings merge logic
Built a new image as follows 
- latest SMD as base 
- modified the …
> Updated CodeEditor entrypoint script for SageMaker's recovery mode

- .github/workflows/build-image.yml
Add missing `\`, right now job fails with `/home/runner/work/_temp/5125d962-0be4-4efa-80e7-9c61d6153773.sh: line 2: --state: command not found`
[Link any related issues here]
[Any additional information that might be helpful for reviewers]
> fix: Add backslash to image build codebuild for multiline
